### ISSUE TITLE
cli and require always tell me about an unexpected token

### ISSUE THREAD

**Issue by xetra11** [simonrenoult/git-log-to-json#3]
That's what I'm doing. My commit messages base on angular standard through commitizen
```
$ gitjson . --subject
undefined:1
['{subject:ci(gulp): extend bump tasks},' '{subject:ci(gulp): add gulp-bump task for versionbump of dockerfil
e, npm, pom},' '{subject:ci(docker): add dockfile to keep track of version},' '{subject:ci(npm): add gulp bum
p as node module},' '{subject:ci(gitignore): add node modules},' '{subject:ci(project): change active spring
boot dependencies},' '{subject:ci(project): initial commit},]
 ^

SyntaxError: Unexpected token '
    at Object.parse (native)
    at C:\Development\ihk\coma\node_modules\git-log-to-json\lib\git-log-to-json.js:35:27
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)

```

**Comment by simonrenoult** [comment]
Thanks, I'll look into it!

**Comment by compulim** [comment]
Same to me, using NPM version `@1.1.1`.
